In [0]:
import numpy as np
import matplotlib.pyplot as plt
import math

In [0]:
aj_m = np.matrix([[0,1,0,0],
                  [0,0,1,0],
                  [0,0,0,1],
                  [0,0,0,0]])

In [146]:
aj_m

matrix([[0, 1, 0, 0],
        [0, 0, 1, 0],
        [0, 0, 0, 1],
        [0, 1, 0, 0]])

In [0]:
# Transitive closure Algorithm for k-hop path
# k-hop = N-1 outer 4 loops. This is because the original D^(1)...
# graph represents the '1-hop' paths so e.g for N = 4 we need 3 more loops to find D^(4)

def transitive_closure_n_hops(aj_m, n_hop):
  the_len = len(aj_m)
  
  aj_m_prev = aj_m
  
  for i in range(n_hop-1):
    aj_m_c = np.matrix([[0]*the_len]*the_len)
    for row in range(the_len):
      for col in range(the_len):
        for k in range(the_len):
          aj_m_c[row,col] = aj_m_c[row,col] or (aj_m[row,k] and aj_m_prev[k,col])
    aj_m_prev = aj_m_c

  return aj_m_prev


  

In [156]:
transitive_closure_n_hops(aj_m,3)

matrix([[0, 0, 0, 1],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [0]:
aj_m_2 = np.matrix([[0,math.inf,3,math.inf],
                  [2,0,5,math.inf],
                  [math.inf,7,0,1],
                  [6,math.inf,9,0]])

In [0]:
def floyd_warshall(a_graph):
  the_len = len(a_graph)
  #the_len = 2  # modify this to find the specific step you are looking for
  for k in range(the_len):
    for row in range(the_len):
      for col in range(the_len):
          a_graph[row,col] = min(a_graph[row,col],(a_graph[row,k] + a_graph[k,col]))

  
  print(a_graph)



In [83]:
floyd_warshall(aj_m_2)

[[ 0. 10.  3.  4.]
 [ 2.  0.  5.  6.]
 [ 7.  7.  0.  1.]
 [ 6. 16.  9.  0.]]


In [0]:
aj_m_3 = np.matrix([[0,math.inf,math.inf,math.inf,-1,math.inf],
                  [1,0,math.inf,2,math.inf,math.inf],
                  [math.inf,2,0,math.inf,math.inf,-8],
                  [-4,math.inf,math.inf,0,-5,math.inf],
                  [math.inf,7,math.inf,math.inf,0,math.inf],
                  [math.inf,5,10,math.inf,math.inf,0]])

In [85]:
floyd_warshall(aj_m_3)

[[ 0.  6. inf  8. -1. inf]
 [-2.  0. inf  2. -3. inf]
 [-5. -3.  0. -1. -6. -8.]
 [-4.  2. inf  0. -5. inf]
 [ 5.  7. inf  9.  0. inf]
 [ 3.  5. 10.  7.  2.  0.]]


In [0]:
aj_m_4 = np.matrix([[0,8,math.inf,math.inf],
                  [8,0,5,3],
                  [math.inf,5,0,6],
                  [math.inf,3,6,0]])

In [87]:
floyd_warshall(aj_m_4)

[[ 0.  8. 13. 11.]
 [ 8.  0.  5.  3.]
 [13.  5.  0.  6.]
 [11.  3.  6.  0.]]


In [0]:
aj_m_5 = np.matrix([[0,math.inf,3,math.inf],
                  [2,0,math.inf,math.inf],
                  [math.inf,7,0,1],
                  [6,math.inf,math.inf,0]])

In [89]:
floyd_warshall(aj_m_5)

[[ 0. 10.  3.  4.]
 [ 2.  0.  5.  6.]
 [ 7.  7.  0.  1.]
 [ 6. 16.  9.  0.]]


In [0]:
aj_m_6 = np.matrix([[0,math.inf,3],
                  [4,0,math.inf],
                  [1,1,0]])

In [91]:
floyd_warshall(aj_m_6)

[[0. 4. 3.]
 [4. 0. 7.]
 [1. 1. 0.]]
