In [0]:
import numpy as np
import matplotlib.pyplot as plt
import math

In [0]:
aj_m = np.matrix([[0,1,0,0],
                  [1,0,0,0],
                  [0,1,0,0],
                  [0,0,1,0]])

In [112]:
aj_m

matrix([[0, 1, 0, 0],
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 1, 0]])

In [0]:
# Transitive closure Algorithm for k-hop path
# k-hop = N-1 outer 4 loops. This is because the original D^(1)...
# graph represents the '1-hop' paths so e.g for N = 4 we need 3 more loops to find D^(4)

def transitive_closure_n_hops(aj_m):
  the_len = len(aj_m)
  for i in range(the_len-1):
    aj_m_c = np.matrix([[0,0,0,0],
                  [0,0,0,0],
                    [0,0,0,0],
                    [0,0,0,0]])
    for row in range(the_len):
      for col in range(the_len):
        for k in range(the_len):
          aj_m_c[row,col] = aj_m_c[row,col] or (aj_m[row,k] and aj_m[k,col])
    aj_m = aj_m_c

  return aj_m


  

In [108]:
transitive_closure_n_hops(aj_m)

matrix([[1, 0, 0, 0],
        [0, 1, 0, 0],
        [1, 0, 0, 0],
        [0, 1, 0, 0]])

In [0]:
aj_m_2 = np.matrix([[0,math.inf,3,math.inf],
                  [2,0,5,math.inf],
                  [math.inf,7,0,1],
                  [6,math.inf,9,0]])

In [0]:
def floyd_warshall(a_graph):
  aj_m_2 = a_graph
  the_len = len(aj_m_2)
  for k in range(the_len):
    for row in range(the_len):
      for col in range(the_len):
          aj_m_2[row,col] = min(aj_m_2[row,col],(aj_m_2[row,k] + aj_m_2[k,col]))

  aj_m_2
  print(aj_m_2)



In [111]:
floyd_warshall(aj_m_2)

[[ 0. 10.  3.  4.]
 [ 2.  0.  5.  6.]
 [ 7.  7.  0.  1.]
 [ 6. 16.  9.  0.]]
